server:
  port: 8083
  servlet:
    context-path: /task/
spring:
  # 数据库连接池
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://${db_host}:${db_port}/${db_database}?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
      username: ${db_username}
      password: ${db_password}
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    platform: mariadb
  # Redis 相关信息配置
  redis:
    host: ${redis_host}
    port: ${redis_port}
    password: ${redis_password}
    database: ${redis_database}
    timeout: 60000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#logback根目录
loghome: /tmp/logs/sports/sports_api
#配置xxl_job
### xxl-job admin address list：调度中心部署跟地址：如调度中心集群部署存在多个地址则用逗号分隔。
# 执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"。
xxl:
  job:
    admin:
      addresses: https://testxxl.xinbosports.com/xxl-job-admin
    ### xxl-job executor address：执行器"AppName"和地址信息配置：AppName执行器心跳注册分组依据；
    # 地址信息用于"调度中心请求并触发任务"和"执行器注册"。
    executor:
      appName: sports-xxl-job-executor
      ### 执行器默认端口为9999，执行器IP默认为空表示自动获取IP，
      # 多网卡时可手动设置指定IP，手动设置IP时将会绑定Host。单机部署多个执行器时，注意要配置不同执行器端口；
      ip:
      port: 9998
      ### xxl-job log path：执行器运行日志文件存储的磁盘位置，需要对该路径拥有读写权限
      logPath: data/applogs/xxl-job/jobhandler
      ### 调度中心日志表数据保存天数 [必填]：过期日志自动清理；限制大于等于7时生效，否则, 如-1，关闭自动清理功能；
      logRetentionDays: 7
    ### xxl-job, access token：执行器通讯TOKEN，非空时启用
    accessToken: